In [1]:
from scipy import linalg
import numpy as np

##  Foundations

In [3]:
A=np.random.randint(1, 10, size=(3,3))
B=np.random.randint(1, 10, size=(3,3))
A,B

(array([[1, 1, 3],
        [6, 2, 5],
        [3, 5, 3]]),
 array([[5, 4, 2],
        [2, 8, 5],
        [9, 3, 3]]))

In [4]:
# Addition
np.add(A,B)

array([[ 6,  5,  5],
       [ 8, 10, 10],
       [12,  8,  6]])

In [5]:
# Subtraction
np.subtract(A,B)

array([[-4, -3,  1],
       [ 4, -6,  0],
       [-6,  2,  0]])

In [6]:
# Multiplication
np.multiply(A,B)

array([[ 5,  4,  6],
       [12, 16, 25],
       [27, 15,  9]])

In [7]:
# Transpose
np.transpose(A)

array([[1, 6, 3],
       [1, 2, 5],
       [3, 5, 3]])

In [8]:
# Inverse
A_inv=linalg.inv(A)
A_inv

array([[-0.38,  0.24, -0.02],
       [-0.06, -0.12,  0.26],
       [ 0.48, -0.04, -0.08]])

In [9]:
# Inverse Rule AA~-1 =A~-1A=I
np.round(np.dot(A,A_inv), decimals=0, out=None)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0., -0.,  1.]])

In [10]:
# Determinant
print(linalg.det(A))

50.0


In [20]:
# Eigen Vector
linalg.eig(A)

(array([ 9.57436524+0.j        , -1.78718262+1.42416874j,
        -1.78718262-1.42416874j]),
 array([[ 0.31095601+0.j        ,  0.38986891+0.33900987j,
          0.38986891-0.33900987j],
        [ 0.68276864+0.j        ,  0.3920946 -0.3896433j ,
          0.3920946 +0.3896433j ],
        [ 0.6611606 +0.j        , -0.6538459 +0.j        ,
         -0.6538459 -0.j        ]]))

In [21]:
# Eigen Value
linalg.eigvals(A)

array([ 9.57436524+0.j        , -1.78718262+1.42416874j,
       -1.78718262-1.42416874j])

In [24]:
np.linalg.matrix_rank(A)

np.int64(3)